### ISSUE TITLE
Upload a static portfolio website on static_portfolio_templates folder.

### ISSUE THREAD

**Issue by akkupy** [akkupy/codeDump#198]

**Comment by SyntaxSmiler03** [comment]
Hello @akkupy 
could you please assign this issue to me?
I will create a static portfolio website using HTML and CSS

**Comment by SyntaxSmiler03** [comment]
under hacktober fest 2023

**Comment by SyntaxSmiler03** [comment]
Do I need to create a new portfolio or just update the existing static one? - @akkupy

**Comment by akkupy** [comment]
Create a new one in a folder. 'akku_portfolio' is just for a demo

**Comment by SyntaxSmiler03** [comment]
Okay. Thank you.

**Comment by Petsamuel** [comment]
assign this task to me

**Comment by Vanshi2504ka** [comment]
Kindly assign me this issue
