### ISSUE TITLE
Implement a data structure program in java

### ISSUE THREAD

**Issue by akkupy** [akkupy/codeDump#209]
Goal is to implement a DSA program in java language and place it in the data_structure folder.

**Comment by SRUJANA2199** [comment]
hi, i would like to work on this can you assign me this?

**Comment by Aniket3063** [comment]
Hello @akkupy,
can you please specify which algorithm i have to write?

I would like to work on it. under hacktoberfest2023

**Comment by akkupy** [comment]
@Aniket3063 Implement Quick Sort

**Comment by iKoNFlair** [comment]
Hello,
Can you please assign me to implement longest consecutive subsequence using dynamic programming?
thanks!!

**Comment by akkupy** [comment]
@iKoNFlair Go ahead!

**Comment by IndranjanaChatterjee** [comment]
Hi, I would like to implement TOWER OF HANOI PROBLEM IN java. Can you please assign it to me for hacktoberfest23?

**Comment by akkupy** [comment]
Create a new issue with title "Tower of Hanoi in Java" I'll assign it to you.. Make sure to place the code in data_structure folder

**Comment by IndranjanaChatterjee** [comment]
ok

**Comment by IndranjanaChatterjee** [comment]
@akkupy I have created a new issue. I will  definitely add the code in the data_structure folder

**Comment by SadeeshaJayaweera** [comment]
@akkupy I Would Like to work on this. Could you please assigned me to this

**Comment by Dhruval7878** [comment]
can i add linkedList code or any sorting algorithm if needed ?

**Comment by Dhruval7878** [comment]
Hello,
Can you please assign me to implement Binary Tree Post-Order Traversal under hacktoberfest2023 ?
thanks!!

**Comment by sneha-4-22** [comment]
@akkupy can i solve  leetcode daily - check in question in java

**Comment by akkupy** [comment]
@Dhruval7878 Create A new Issue and I'll Assign it to you

**Comment by akkupy** [comment]
@sneha-4-22 Yes you can ! Create a new issue if you need to be assigned .

**Comment by ronitsharma03** [comment]
@akkupy Can you please assign me to implement bubble sort program in java under hacktoberfest2023 ?

**Comment by akkupy** [comment]
@ronitsharma03 Create a new issue. and I'll assign it to you

**Comment by ronitsharma03** [comment]
@akkupy Okay!

**Comment by ronitsharma03** [comment]
@akkupy Do i have to add any labels?!

**Comment by akkupy** [comment]
@ronitsharma03 I'll add the neccessary labels.

**Comment by Hrishap** [comment]
Hello @akkupy sir 
I would like to work on this .Can you please assign me this 
thank you

**Comment by SadeeshaJayaweera** [comment]
Please Check and Merge the Solution that i have implemented for this issue. 
Thank You & Happy Coding ✌️🧑‍💻

**Comment by iKoNFlair** [comment]
> @iKoNFlair Go ahead!

Sir, I have implemented the program but the pull request wasn't merged :(

**Comment by akkupy** [comment]
@iKoNFlair Check Again..If not merged, it might have an issue...Discuss on PR
