### ISSUE TITLE
Daily LeetCode Check-In Challenge - [Date] - Upload Your Solutions

### ISSUE THREAD

**Issue by sneha-4-22** [akkupy/codeDump#289]
### Description
Let's solve  a LeetCode question in Java every day,  to improve our problem-solving skills and Java programming abilities.

### Plan
- Programming Language: Java
- Focus: Medium difficulty questions, data structures, and algorithms.

### Folder Structure
- LeetCode Questions
  - Question-123-Solution
    - Main.java
    - Explanation.md (optional)
  - Question-456-Solution
    - Main.java
    - Explanation.md (optional)

Let's learn, grow, and build a repository of solutions together!

**Comment by akkupy** [comment]
@sneha-4-22  You can create a folder in the root directory named 'leetCodeQuestions' and place your work there.

**Comment by akkupy** [comment]
@sneha-4-22 I have added a README.md in LeetCodeQuestions folder that you have created..Maintain that Readme with necessary info about the code you are adding on that folder

**Comment by sneha-4-22** [comment]
@akkupy ok Thanks

**Comment by Aniket3063** [comment]
I want to upload today's(2/10/2023) leetcode daily Challenge problem ([2038. Remove Colored Pieces if Both Neighbors are the Same Color](https://leetcode.com/problems/remove-colored-pieces-if-both-neighbors-are-the-same-color/)) in Cpp.
please assign it.
