### ISSUE TITLE
 Request to Add Linked List Operations in Python

### ISSUE THREAD

**Issue by arun-h** [akkupy/codeDump#305]
Hey Akash,

I noticed the absence of linked list operations in the "Data Structure" folder. Would you consider adding Python implementations? I'm willing to contribute. Let me know if you're open to this.

Thanks,
Arun

**Comment by akkupy** [comment]
You can work on that.

**Comment by arun-h** [comment]
Thank u for the green light! Before I start working on the linked list operations code, could you please clarify the preferred location? Should I add the code under:

data_structure > linkedlist > operations_code OR
python > linkedlist > operations_code

**Comment by akkupy** [comment]
Place it on data_structure - linkedlist - operations_code

**Comment by arun-h** [comment]
I appreciate your guidance
