### ISSUE TITLE
I want to add some most useful algorithms code Like 

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [akkupy/codeDump#415]
1) K-way merge Algorithm

2) Stack Reduced Quick Sort

3) Merge sort combined with Insertion Sort

4) Prims, Topological, Kruskal's algorithm

5) DijKstra , Floyd Warshall ,bellman ford algorithm

6) Backtracking
a) Rat Maze
b) N-Queen
c) Sudoku
d) Sum of Subset

7) Activity selection , Huffman Encoding .

Please consider this under Hacktoberfest_2023 , I am interested to Contribute my self : )

**Comment by Bharath-KumarReddy** [comment]
Hello sir Greetings ,
As the issue #415  [ I want to add some most useful algorithms ]
Please provide me access so that I can make Pull request ,

It is Showing error , Permission denied
[image: image.png]


Please consider this under Hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
Hello sir/mam Greetings ,
As the issue [#415](https://github.com/akkupy/Code_Dump/issues/415)  [ I want to add some most useful algorithms ]
Please provide me access so that I can make Pull request ,

It is Showing error , Permission denied

![image](https://github.com/akkupy/Code_Dump/assets/127650446/4262d761-ff46-4ca1-a06b-8800273bef21)



Please consider this under Hacktoberfest_23 : )

**Comment by akkupy** [comment]
Fork this repo and push it into the forked repo and Create a PR
