### ISSUE TITLE
Website to showcase the properties of CSS Flex Box

### ISSUE THREAD

**Issue by SadeeshaJayaweera** [akkupy/codeDump#462]
i would like to contribute a Website which show case all the properties of the css flexbox which is developed only using html and css. 

**Key Features:**

1. **Interactive Demos:** The website will include interactive examples and demos that illustrate how different Flexbox properties work in real-time. Users can experiment with various settings and see the immediate visual impact.

2. **Detailed Documentation:** Each Flexbox property and concept will be explained in detail, along with code snippets and usage guidelines. This documentation will cater to both beginners and experienced developers.

3. **Responsive Design:** To demonstrate Flexbox's versatility, the website itself will be built using Flexbox, ensuring a responsive and user-friendly experience on various devices.

4. **Tutorials and Guides:** In addition to demos and documentation, the website will offer tutorials and step-by-step guides on common Flexbox layouts and best practices.

Please consider this under Hacktoberfest_23

Thank You @akkupy

**Comment by barkhayadav12** [comment]
Hi, I would like to work on this issue. Can you please assign it to me.

**Comment by SadeeshaJayaweera** [comment]
@akkupy Please review the PR and Close the issue. 
Thanks & Happy Coding
