### ISSUE TITLE
excluded from hacktoberfest2023

### ISSUE THREAD

**Issue by kondapalli19** [akkupy/codeDump#615]
![Screenshot 2023-10-02 214737](https://github.com/akkupy/codeDump/assets/101511737/052b5955-02ee-4b6c-8a94-3a33736dcc84)

**Comment by akkupy** [comment]
Sorry for the inconvenience, As I mentioned in the readme that this repo no longer contribute to Hacktoberfest...Kaindly Refer the Readme for a repo that does contribute to Hacktoberfest
